apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# patches:
#   - path: ./configmap.yml
#   - path: ./pvc.yml
#   - path: ./deployment.yml
#   - path: ./service.yml
resources:
  - ../../base
images:
  - name: chagchagchag/fibonacci-backend-cache
  - newName: chagchagchag/fibonacci-backend-cache
  - newTag: 0.0.1-fibonacci-backend-cache.01
namespace: fibonacci-develop